import Head from 'next/head';
import Image from 'next/image';

// Global state
import { useGlobalStore } from '../zustand-state/globalState';

export default function Home() {
	const updateNavbar = useGlobalStore((state) => state.updateNavbar);
	const updateFooter = useGlobalStore((state) => state.updateFooter);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="text-6xl font-black">Home</h1>
		</div>
	);
}
